//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordSlide {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordSlide.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string AllButton {
            get {
                return ResourceManager.GetString("AllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Default Lines Per Slide for {0}.
        /// </summary>
        internal static string DefaultLocalLinesPerSlide {
            get {
                return ResourceManager.GetString("DefaultLocalLinesPerSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Backward one slide.
        /// </summary>
        internal static string Help_backwardButton {
            get {
                return ResourceManager.GetString("Help_backwardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Backward one song.
        /// </summary>
        internal static string Help_backwardSongButton {
            get {
                return ResourceManager.GetString("Help_backwardSongButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Backward one verse.
        /// </summary>
        internal static string Help_backwardVerseButton {
            get {
                return ResourceManager.GetString("Help_backwardVerseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Toggle blank screen.
        /// </summary>
        internal static string Help_blankButton {
            get {
                return ResourceManager.GetString("Help_blankButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Show chorus.
        /// </summary>
        internal static string Help_chorusButton {
            get {
                return ResourceManager.GetString("Help_chorusButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Exit.
        /// </summary>
        internal static string Help_exitButton {
            get {
                return ResourceManager.GetString("Help_exitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Forward one slide.
        /// </summary>
        internal static string Help_forwardButton {
            get {
                return ResourceManager.GetString("Help_forwardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Forward one song.
        /// </summary>
        internal static string Help_forwardSongButton {
            get {
                return ResourceManager.GetString("Help_forwardSongButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Forward one verse.
        /// </summary>
        internal static string Help_forwardVerseButton {
            get {
                return ResourceManager.GetString("Help_forwardVerseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Show this help.
        /// </summary>
        internal static string Help_helpButton {
            get {
                return ResourceManager.GetString("Help_helpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Test video boundaries.
        /// </summary>
        internal static string Help_videoTestButton {
            get {
                return ResourceManager.GetString("Help_videoTestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid WordSlide data file. It may be corrupted or from a newer version of WordSlide..
        /// </summary>
        internal static string InvalidFileError {
            get {
                return ResourceManager.GetString("InvalidFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid File.
        /// </summary>
        internal static string InvalidFileTitle {
            get {
                return ResourceManager.GetString("InvalidFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your library contains {0} slide sets..
        /// </summary>
        internal static string LibraryCountLabel {
            get {
                return ResourceManager.GetString("LibraryCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Library.
        /// </summary>
        internal static string LibraryImportForm {
            get {
                return ResourceManager.GetString("LibraryImportForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The slide library you selected contains {0} slide sets..
        /// </summary>
        internal static string LibraryImportLabel {
            get {
                return ResourceManager.GetString("LibraryImportLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the sets below that you wish to import..
        /// </summary>
        internal static string LibraryImportPrompt {
            get {
                return ResourceManager.GetString("LibraryImportPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines Per Slide for {0}.
        /// </summary>
        internal static string LocalLinesPerSlide {
            get {
                return ResourceManager.GetString("LocalLinesPerSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string NoButton {
            get {
                return ResourceManager.GetString("NoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select None.
        /// </summary>
        internal static string NoneButton {
            get {
                return ResourceManager.GetString("NoneButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No to All.
        /// </summary>
        internal static string NtaButton {
            get {
                return ResourceManager.GetString("NtaButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite.
        /// </summary>
        internal static string OverwriteForm {
            get {
                return ResourceManager.GetString("OverwriteForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists in your library..
        /// </summary>
        internal static string OverwriteWarning {
            get {
                return ResourceManager.GetString("OverwriteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to overwrite?.
        /// </summary>
        internal static string OverwriteWarningQuestion {
            get {
                return ResourceManager.GetString("OverwriteWarningQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string YesButton {
            get {
                return ResourceManager.GetString("YesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes to All.
        /// </summary>
        internal static string YtaButton {
            get {
                return ResourceManager.GetString("YtaButton", resourceCulture);
            }
        }
    }
}
